FROM golang:1.25-alpine AS builder
WORKDIR /app
COPY . .
RUN go mod tidy && go build -o room ./room

FROM alpine:3.18
WORKDIR /app
COPY --from=builder /app/room .
EXPOSE 8080
CMD ["./room"]
